import { StyleSheet, Dimensions } from "react-native";
import { theme } from "../../theme";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.screen,
  },
  scrollContent: {
    paddingTop: theme.spacing.space[40],
    paddingBottom: theme.spacing.space[100],
    paddingHorizontal: theme.spacing.lg,
  },
  header: {
    alignItems: "center",
    marginBottom: theme.spacing.xl,
    paddingHorizontal: theme.spacing.md,
  },
  backButton: {
    position: "absolute",
    left: 0,
    top: 0,
    padding: theme.spacing.sm,
    zIndex: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: theme.colors.text.primary,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing.xs,
    textAlign: "center",
    fontWeight: "500",
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.spacing["4xl"],
  },
  loadingText: {
    color: theme.colors.text.secondary,
    marginTop: theme.spacing.md,
    fontSize: 16,
  },
  errorContainer: {
    backgroundColor: theme.colors.status.errorBg,
    padding: theme.spacing.lg,
    borderRadius: 12,
    marginBottom: theme.spacing.lg,
  },
  errorText: {
    color: theme.colors.status.errorText,
    fontSize: 14,
    textAlign: "center",
    fontWeight: "600",
  },
  // Date Filters Section
  filtersContainer: {
    backgroundColor: theme.colors.background.surface,
    padding: theme.spacing.lg,
    borderRadius: 16,
    marginBottom: theme.spacing.lg,
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  filtersTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.text.primary,
    marginBottom: theme.spacing.md,
  },
  dateInputsRow: {
    flexDirection: "row",
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  dateInputWrapper: {
    flex: 1,
  },
  dateLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: theme.colors.text.muted,
    marginBottom: theme.spacing.xs,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  dateButton: {
    backgroundColor: theme.colors.background.subtle,
    padding: theme.spacing.md,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border.subtle,
  },
  dateButtonText: {
    fontSize: 14,
    color: theme.colors.text.primary,
    fontWeight: "500",
  },
  applyButton: {
    backgroundColor: theme.colors.action.infoBg,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  applyButtonText: {
    color: theme.colors.action.primaryText,
    fontSize: 15,
    fontWeight: "700",
  },
  // Stats Cards
  statsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: theme.spacing.md,
    gap: theme.spacing.sm,
  },
  statCard: {
    flex: 1,
    minWidth: "48%",
    backgroundColor: theme.colors.background.surface,
    padding: theme.spacing.lg,
    paddingVertical: theme.spacing.xl,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 120,
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  statValue: {
    fontSize: 22,
    fontWeight: "700",
    color: theme.colors.text.primary,
    marginTop: theme.spacing.sm,
    marginBottom: theme.spacing.xs,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
    letterSpacing: -0.5,
  },
  statValueNegative: {
    color: theme.colors.status.danger,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.colors.text.muted,
    marginTop: theme.spacing.xs,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  // Charts Section
  chartSection: {
    marginBottom: theme.spacing.xl,
  },
  chartContainer: {
    backgroundColor: theme.colors.background.surface,
    padding: theme.spacing.lg,
    borderRadius: 16,
    marginBottom: theme.spacing.lg,
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.text.primary,
    marginBottom: theme.spacing.lg,
  },
  chartWrapper: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.spacing.md,
  },
  emptyChartContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.spacing["3xl"],
  },
  emptyChartText: {
    fontSize: 14,
    color: theme.colors.text.muted,
    marginTop: theme.spacing.md,
    textAlign: "center",
  },
  legendContainer: {
    marginTop: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border.subtle,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: theme.spacing.xs,
  },
  legendLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  legendColor: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginRight: theme.spacing.sm,
  },
  legendLabel: {
    fontSize: 13,
    color: theme.colors.text.primary,
    fontWeight: "500",
    flex: 1,
  },
  legendValue: {
    fontSize: 13,
    color: theme.colors.text.secondary,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  emptyState: {
    backgroundColor: theme.colors.background.surface,
    padding: theme.spacing["3xl"],
    paddingVertical: theme.spacing["4xl"],
    borderRadius: 16,
    alignItems: "center",
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  emptyStateText: {
    fontSize: 16,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing.md,
    fontWeight: "600",
    textAlign: "center",
  },
  emptyStateSubtext: {
    fontSize: 13,
    color: theme.colors.text.muted,
    marginTop: theme.spacing.xs,
    textAlign: "center",
    lineHeight: 18,
  },
});

