import { StyleSheet } from "react-native";
import { theme } from "../../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.screen,
  },
  scrollContent: {
    paddingTop: theme.spacing.space[60],
    paddingBottom: theme.spacing.space[100],
    paddingHorizontal: theme.spacing.xl,
  },
  header: {
    alignItems: "center",
    marginBottom: theme.spacing["3xl"],
  },
  title: {
    ...theme.typography.textStyles.title,
    color: theme.colors.text.primary,
    marginTop: theme.spacing.lg,
  },
  subtitle: {
    ...theme.typography.textStyles.body,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing.sm,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: theme.spacing.lg,
  },
  statCard: {
    flex: 1,
    backgroundColor: theme.colors.background.surface,
    padding: theme.spacing.xl,
    borderRadius: theme.spacing.md,
    alignItems: "center",
    marginHorizontal: theme.spacing.space[6],
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statValue: {
    fontSize: theme.typography.fontSize.xl,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.text.primary,
    marginTop: theme.spacing.sm,
  },
  statLabel: {
    ...theme.typography.textStyles.caption,
    color: theme.colors.text.muted,
    marginTop: theme.spacing.space[4],
  },
  statSubLabel: {
    fontSize: 11,
    color: theme.colors.text.disabled,
    marginTop: theme.spacing.space[2],
  },
  statValueNegative: {
    color: theme.colors.status.danger,
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.spacing["4xl"],
  },
  loadingText: {
    ...theme.typography.textStyles.body,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing.md,
  },
  actionsContainer: {
    marginTop: theme.spacing.xl,
    marginBottom: theme.spacing["3xl"],
  },
  sectionTitle: {
    ...theme.typography.textStyles.sectionTitle,
    color: theme.colors.text.primary,
    marginBottom: theme.spacing.lg,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.action.infoBg,
    paddingVertical: theme.spacing.lg,
    borderRadius: theme.spacing.md,
    marginBottom: theme.spacing.md,
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  actionButtonSuccess: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.status.success,
    paddingVertical: theme.spacing.lg,
    borderRadius: theme.spacing.md,
    marginBottom: theme.spacing.md,
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  actionButtonDanger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.action.infoBg,
    paddingVertical: theme.spacing.lg,
    borderRadius: theme.spacing.md,
    marginBottom: theme.spacing.md,
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  actionButtonSecondary: {
    backgroundColor: theme.colors.background.surface,
    borderWidth: 2,
    borderColor: theme.colors.action.infoBg,
  },
  actionButtonText: {
    ...theme.typography.textStyles.button,
    color: theme.colors.action.infoText,
    marginLeft: theme.spacing.sm,
  },
  actionButtonTextSuccess: {
    ...theme.typography.textStyles.button,
    color: theme.colors.action.primaryText,
    marginLeft: theme.spacing.sm,
  },
  actionButtonTextDanger: {
    ...theme.typography.textStyles.button,
    color: theme.colors.action.primaryText,
    marginLeft: theme.spacing.sm,
  },
  actionButtonTextSecondary: {
    color: theme.colors.action.infoBg,
  },
  activityContainer: {
    marginBottom: theme.spacing.xl,
  },
  emptyState: {
    backgroundColor: theme.colors.background.surface,
    padding: theme.spacing["5xl"],
    borderRadius: theme.spacing.md,
    alignItems: "center",
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  emptyStateText: {
    ...theme.typography.textStyles.body,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing.lg,
    fontWeight: theme.typography.fontWeight.semibold,
  },
  emptyStateSubtext: {
    ...theme.typography.textStyles.caption,
    color: theme.colors.text.muted,
    marginTop: theme.spacing.sm,
    textAlign: "center",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: theme.colors.background.surface,
    paddingHorizontal: theme.spacing.xl,
    paddingVertical: theme.spacing.lg,
    paddingBottom: theme.spacing["3xl"],
    borderTopWidth: 1,
    borderTopColor: theme.colors.border.subtle,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.status.danger,
    paddingVertical: theme.spacing.space[14],
    borderRadius: theme.spacing.md,
  },
  logoutButtonText: {
    ...theme.typography.textStyles.button,
    color: theme.colors.action.primaryText,
    marginLeft: theme.spacing.sm,
  },
});


