import { StyleSheet } from "react-native";
import { theme } from "../../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.screen,
  },
  scrollContent: {
    paddingTop: theme.spacing.space[40],
    paddingBottom: theme.spacing.space[100],
    paddingHorizontal: theme.spacing.lg,
  },
  header: {
    alignItems: "center",
    marginBottom: theme.spacing["2xl"],
    paddingHorizontal: theme.spacing.md,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: theme.colors.text.primary,
    marginTop: theme.spacing.md,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing.xs,
    textAlign: "center",
    fontWeight: "500",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: theme.spacing.md,
    gap: theme.spacing.sm,
  },
  statCard: {
    flex: 1,
    backgroundColor: theme.colors.background.surface,
    padding: theme.spacing.lg,
    paddingVertical: theme.spacing.xl,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 140,
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  statValue: {
    fontSize: 24,
    fontWeight: "700",
    color: theme.colors.text.primary,
    marginTop: theme.spacing.md,
    marginBottom: theme.spacing.xs,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
    letterSpacing: -0.5,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: theme.colors.text.muted,
    marginTop: theme.spacing.xs,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  statSubLabel: {
    fontSize: 10,
    color: theme.colors.text.disabled,
    marginTop: theme.spacing.space[4],
    textAlign: "center",
  },
  statValueNegative: {
    color: theme.colors.status.danger,
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.spacing["4xl"],
  },
  loadingText: {
    ...theme.typography.textStyles.body,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing.md,
  },
  actionsContainer: {
    marginTop: theme.spacing["2xl"],
    marginBottom: theme.spacing["2xl"],
    paddingHorizontal: theme.spacing.xs,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: theme.colors.text.primary,
    marginBottom: theme.spacing.lg,
    paddingHorizontal: theme.spacing.xs,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.action.infoBg,
    paddingVertical: 16,
    borderRadius: 12,
    marginBottom: theme.spacing.sm,
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  actionButtonSuccess: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.status.success,
    paddingVertical: 16,
    borderRadius: 12,
    marginBottom: theme.spacing.sm,
    shadowColor: theme.colors.status.success,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  actionButtonDanger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.status.danger,
    paddingVertical: 16,
    borderRadius: 12,
    marginBottom: theme.spacing.sm,
    shadowColor: theme.colors.status.danger,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  actionButtonSecondary: {
    backgroundColor: theme.colors.background.surface,
    borderWidth: 1.5,
    borderColor: theme.colors.border.subtle,
    shadowOpacity: 0.05,
    elevation: 1,
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: theme.colors.action.infoText,
    marginLeft: theme.spacing.sm,
  },
  actionButtonTextSuccess: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
    marginLeft: theme.spacing.sm,
  },
  actionButtonTextDanger: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
    marginLeft: theme.spacing.sm,
  },
  actionButtonTextSecondary: {
    color: theme.colors.text.secondary,
    fontWeight: "600",
  },
  activityContainer: {
    marginBottom: theme.spacing.xl,
    paddingHorizontal: theme.spacing.xs,
  },
  emptyState: {
    backgroundColor: theme.colors.background.surface,
    padding: theme.spacing["3xl"],
    paddingVertical: theme.spacing["4xl"],
    borderRadius: 16,
    alignItems: "center",
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  emptyStateText: {
    fontSize: 16,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing.md,
    fontWeight: "600",
    textAlign: "center",
  },
  emptyStateSubtext: {
    fontSize: 13,
    color: theme.colors.text.muted,
    marginTop: theme.spacing.xs,
    textAlign: "center",
    lineHeight: 18,
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: theme.colors.background.surface,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    paddingBottom: theme.spacing["3xl"],
    borderTopWidth: 1,
    borderTopColor: theme.colors.border.subtle,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 5,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    paddingVertical: 12,
    borderRadius: 8,
  },
  logoutButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: theme.colors.status.danger,
    marginLeft: theme.spacing.xs,
  },
  // Transaction styles
  transactionsList: {
    backgroundColor: theme.colors.background.surface,
    borderRadius: 16,
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    overflow: "hidden",
  },
  transactionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: theme.spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border.subtle,
  },
  transactionLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  transactionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginRight: theme.spacing.md,
  },
  transactionDetails: {
    flex: 1,
  },
  transactionDescription: {
    fontSize: 15,
    fontWeight: "600",
    color: theme.colors.text.primary,
    marginBottom: 2,
  },
  transactionDate: {
    fontSize: 12,
    color: theme.colors.text.muted,
  },
  transactionAmount: {
    fontSize: 16,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  transactionAmountIncome: {
    color: theme.colors.status.success,
  },
  transactionAmountExpense: {
    color: theme.colors.status.danger,
  },
});
