import { StyleSheet } from "react-native";
import { theme } from "../../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.screen,
  },
  scrollContent: {
    padding: theme.spacing.lg,
    paddingTop: theme.spacing.space[60],
    paddingBottom: theme.spacing["4xl"],
  },
  header: {
    marginBottom: theme.spacing["2xl"],
  },
  title: {
    fontSize: 32,
    fontWeight: "700",
    color: theme.colors.text.primary,
    marginBottom: theme.spacing.xs,
  },
  subtitle: {
    fontSize: 16,
    color: theme.colors.text.secondary,
  },
  card: {
    backgroundColor: theme.colors.background.surface,
    borderRadius: 16,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.md,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing.sm,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  amountInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: theme.colors.status.danger,
    paddingBottom: theme.spacing.sm,
  },
  currencySymbol: {
    fontSize: 28,
    fontWeight: "700",
    color: theme.colors.status.danger,
    marginRight: theme.spacing.sm,
  },
  amountInput: {
    flex: 1,
    fontSize: 32,
    fontWeight: "700",
    color: theme.colors.text.primary,
    padding: 0,
  },
  categoryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: theme.colors.background.screen,
    borderRadius: 12,
    padding: theme.spacing.md,
    minHeight: 56,
  },
  selectedCategoryContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  categoryIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: theme.spacing.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryColorIndicator: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: theme.spacing.sm,
  },
  categoryButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: theme.colors.text.primary,
  },
  categoryButtonPlaceholder: {
    fontSize: 16,
    color: theme.colors.text.muted,
  },
  chevron: {
    fontSize: 28,
    color: theme.colors.text.muted,
    fontWeight: "300",
  },
  textArea: {
    backgroundColor: theme.colors.background.screen,
    borderRadius: 12,
    padding: theme.spacing.md,
    fontSize: 16,
    color: theme.colors.text.primary,
    minHeight: 100,
    textAlignVertical: "top",
  },
  dateButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.background.screen,
    borderRadius: 12,
    padding: theme.spacing.md,
    minHeight: 56,
  },
  dateIcon: {
    fontSize: 24,
    marginRight: theme.spacing.sm,
  },
  dateButtonText: {
    fontSize: 16,
    fontWeight: "500",
    color: theme.colors.text.primary,
  },
  messageError: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.status.errorBg,
    borderRadius: 12,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.md,
    borderLeftWidth: 4,
    borderLeftColor: theme.colors.status.danger,
  },
  messageSuccess: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.status.successBg,
    borderRadius: 12,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.md,
    borderLeftWidth: 4,
    borderLeftColor: theme.colors.status.success,
  },
  messageIcon: {
    fontSize: 20,
    marginRight: theme.spacing.sm,
  },
  messageText: {
    fontSize: 14,
    color: theme.colors.text.primary,
    flex: 1,
  },
  button: {
    backgroundColor: theme.colors.status.danger,
    paddingVertical: theme.spacing.lg,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: theme.spacing.lg,
    shadowColor: theme.colors.status.danger,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  secondaryButton: {
    paddingVertical: theme.spacing.lg,
    alignItems: "center",
    justifyContent: "center",
    marginTop: theme.spacing.sm,
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: theme.colors.text.secondary,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: theme.colors.background.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "80%",
    paddingBottom: theme.spacing["2xl"],
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: theme.spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border.subtle,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: theme.colors.text.primary,
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.background.screen,
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseText: {
    fontSize: 20,
    color: theme.colors.text.secondary,
  },
  categoryItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: theme.spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border.subtle,
  },
  categoryItemSelected: {
    backgroundColor: theme.colors.background.screen,
  },
  categoryItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  categoryIconContainerLarge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: theme.spacing.md,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryColorDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: theme.spacing.md,
  },
  categoryItemName: {
    fontSize: 16,
    fontWeight: "500",
    color: theme.colors.text.primary,
  },
  checkmark: {
    fontSize: 20,
    color: theme.colors.status.success,
    fontWeight: "700",
  },
  emptyState: {
    padding: theme.spacing["2xl"],
    alignItems: "center",
  },
  emptyStateText: {
    fontSize: 16,
    color: theme.colors.text.secondary,
    textAlign: "center",
  },
  clearCategoryButton: {
    marginHorizontal: theme.spacing.lg,
    marginTop: theme.spacing.md,
    paddingVertical: theme.spacing.md,
    alignItems: "center",
    borderRadius: 12,
    backgroundColor: theme.colors.background.screen,
  },
  clearCategoryText: {
    fontSize: 16,
    fontWeight: "600",
    color: theme.colors.text.secondary,
  },
});
